version: "3.9"

services:
  db:
    image: postgres:12-alpine
    container_name: fastapiapp_silent_site
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - fastapiappnetwork

  redis:
    image: redis:6.2
    container_name: fastapiapp_silent_site_redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - fastapiappnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - "1234:8080"
    networks:
      - fastapiappnetwork

networks:
  fastapiappnetwork: