"""Add nome to user 2

Revision ID: 8d6478875e2a
Revises: d7d5172c5f3f
Create Date: 2024-12-07 23:28:51.158437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8d6478875e2a'
down_revision: Union[str, None] = 'd7d5172c5f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'participant_name_2',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('room', 'participant_photo_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'participant_photo_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('room', 'participant_name_2',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
