"""Add table user

Revision ID: 901e6eda2af8
Revises: 8d6478875e2a
Create Date: 2024-12-09 18:03:04.558013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '901e6eda2af8'
down_revision: Union[str, None] = '8d6478875e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('room', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['room'], ['room.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('room', 'participant_photo_2')
    op.drop_column('room', 'participant_name_1')
    op.drop_column('room', 'is_waiting')
    op.drop_column('room', 'participant_photo_1')
    op.drop_column('room', 'participant_name_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('participant_name_2', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('participant_photo_1', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('room', sa.Column('is_waiting', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('room', sa.Column('participant_name_1', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('room', sa.Column('participant_photo_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('user')
    # ### end Alembic commands ###
